using System.Collections.Generic;

namespace HexLive.Simulation.Content
{
    /// <summary>
    /// Where a garment physically SITS on the body — the fine-grained wear slot
    /// model, mirrored from the prefab (`Wear.slots`, the presentation's
    /// authority for what displaces what: `BodyBones.Equip` keeps one garment
    /// per (layer, slot)).
    ///
    /// <b>Why this exists.</b> The sim's <see cref="ObjectDefinition.Covers"/> is
    /// a list of 7 coarse <see cref="BodyPart"/> zones and means "what this
    /// garment PROTECTS / covers" — armor absorption, warmth, sun, wound stains.
    /// It was long doubled up as an occupancy test ("same layer + overlapping
    /// part ⇒ take the old piece off"), which is far too blunt: a thigh holster,
    /// stockings and boots all report `LegL+LegR`, so donning boots stripped the
    /// holster, panties stripped tights and a necklace stripped a bra — 61 such
    /// false pairs across the wardrobe. Slots tell them apart (`ThighR` vs
    /// `ShinR/L` vs `FootR/L`).
    ///
    /// <b>Direction of truth (was written backwards in the spec).</b> The PREFAB
    /// is authoritative; this table mirrors it. Never "fix" a prefab by
    /// coarsening its slots to match `Covers` — that destroys the finer data.
    /// After editing a prefab's slots, update the matching row here.
    ///
    /// A garment with no row falls back to the old `Covers` test, so
    /// unauthored art keeps its previous behaviour instead of stacking freely.
    /// </summary>
    public static class WearSlotCatalog
    {
        // Mirrors HexLive.UnityPresentation.Wearing.VisualWearSlot 1:1 (order
        // matters only for readability; matching NAMES are what the sweep uses).
        private static readonly Dictionary<string, WearSlot[]> Slots = new()
        {
            // §72: снаряжение чужака. Слоты взяты ИЗ ПРЕФАБОВ (§52.9 —
            // вытеснение решают слоты, а не Covers), поэтому портупея и
            // поддоспешник оба Chest и вытесняют друг друга по слоям, а
            // набедренники и наколенники живут раздельно.
            ["TonnyFlash"] = new[] { WearSlot.Chest },
            ["FAO Harness Male"] = new[] { WearSlot.Chest },
            ["FCO Belt Male"] = new[] { WearSlot.Belly },
            ["FCO Boots Male"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["FCO Gloves Male"] = new[] { WearSlot.HandR, WearSlot.HandL },
            ["FCO Knee Straps Male"] = new[] { WearSlot.ShinR, WearSlot.ShinL },
            ["FCO Legs Straps Male"] = new[] { WearSlot.ThighR, WearSlot.ThighL },
            ["FCO Pants Male"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["FCO Waist Strappy Male"] = new[] { WearSlot.Pelvis },
            // ["Boots 20496"] — prefab authors NO slots; falls back to Covers.
            ["clothing.ankleboots_amy"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.armguards_fighter"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.armwraps_primal"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.armwraps_primal_sleeve1"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.armwraps_primal_sleeve2"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.armwraps_primal_sleeve3"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.babydoll_sweety"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.babydoll_sweety_01babydoll"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.babydoll_sweety_02_babydoll"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.babydoll_sweety_03_babydoll"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.babydoll_sweety_04babydoll"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.babydoll_sweety_05babydoll"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.babydoll_sweety_06_babydoll"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.babydoll_sweety_07_babydoll"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.babydoll_tod"] = new[] { WearSlot.Chest },
            ["clothing.belt_anarchy"] = new[] { WearSlot.Pelvis },
            ["clothing.belt_cindy"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.belt_fighter"] = new[] { WearSlot.Belly },
            ["clothing.belt_holster"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.belt_stars"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.blouse_anarchy"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.blouse_nerd"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.blouse_riot"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.blouse_riot_denim"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.blouse_riot_green"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.blouse_riot_squaresclear"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.blouse_waist_riot"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.blouse_waist_riot_denim"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.blouse_waist_riot_green"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.blouse_waist_riot_squaresclear"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.boots_alloy"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_anarchy"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_anarchy_purple"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_anarchy_red"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_latex_blue"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_latex_grey"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_latex_pink"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_latex_red"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_latex_white"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_leather_beige"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_leather_black"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_leather_blue"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_leather_brown"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_leather_grey"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_leather_red"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_velvet_beige"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_velvet_black"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_velvet_blue"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_velvet_brown"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_velvet_purple"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_charm_velvet_red"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_cindy"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_classic"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_black_red_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_black_white_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_black_yellow_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_red_black_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_red_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_red_white_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_red_yellow_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_white_black_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_white_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_white_red_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_white_yellow_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_yellow_black_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_yellow_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_yellow_red_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_leather_lb_yellow_white_leather"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_osiris"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_ranger"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.boots_riot"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.bowtie_nerd"] = new[] { WearSlot.Neck },
            ["clothing.bracelet_luxury"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.cap_anarchy"] = new[] { WearSlot.Head },
            ["clothing.cap_anarchy_black"] = new[] { WearSlot.Head },
            ["clothing.cap_anarchy_brown"] = new[] { WearSlot.Head },
            ["clothing.cap_anarchy_purple"] = new[] { WearSlot.Head },
            ["clothing.cap_riot"] = new[] { WearSlot.Head },
            ["clothing.cap_riot_camel"] = new[] { WearSlot.Head },
            ["clothing.cap_riot_denim"] = new[] { WearSlot.Head },
            ["clothing.cap_riot_red"] = new[] { WearSlot.Head },
            ["clothing.cap_stars"] = new[] { WearSlot.Head },
            ["clothing.collar_anarchy"] = new[] { WearSlot.Neck },
            ["clothing.collar_anarchy_brn"] = new[] { WearSlot.Neck },
            ["clothing.collar_fur"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.collar_fur_color01"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.collar_fur_color02"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.collar_fur_color03"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.collar_fur_color04"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.collar_fur_color05"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.collar_fur_color06"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.collar_studded_anarchy"] = new[] { WearSlot.Neck },
            ["clothing.collar_studded_anarchy_black"] = new[] { WearSlot.Neck },
            ["clothing.corset_anarchy"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.corset_anarchy_red"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.corset_skinny"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.croptop_fit"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_1_blackblue"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_1_blacklime"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_1_blackpink"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_1_blackwhite"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_1_blue"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_1_lime"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_1_pink"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_1_white"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_2_black"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_black"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_black2"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_blackgreen"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_blackmagenta"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_blackorange"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_magenta"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_orange"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_turquoise"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_3_white"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_4_batik1"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_4_batik2"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_4_batik3"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_4_batik4"] = new[] { WearSlot.Chest },
            ["clothing.croptop_fit_4_batik5"] = new[] { WearSlot.Chest },
            ["clothing.croptop_idol"] = new[] { WearSlot.Chest },
            ["clothing.croptop_idol_blue"] = new[] { WearSlot.Chest },
            ["clothing.cuffs_anarchy"] = new[] { WearSlot.WristR, WearSlot.WristL },
            ["clothing.dress_city"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_city_02_dress"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_city_03_dress"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_city_04_dress"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_city_05_dress"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_city_06_dress"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_city_07_dress"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_night"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.dress_night_red"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.dress_night_white"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.dress_primal"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_primal_color01"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_primal_color02"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_primal_color03"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_primal_color04"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_primal_color05"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.dress_primal_color06"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.footwear_fighter"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.glasses_nerd"] = new[] { WearSlot.Head },
            ["clothing.gloves_biker"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL, WearSlot.HandR, WearSlot.HandL },
            ["clothing.gloves_cindy"] = new[] { WearSlot.WristR, WearSlot.WristL, WearSlot.HandR, WearSlot.HandL },
            ["clothing.gloves_classic"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL, WearSlot.HandR, WearSlot.HandL },
            ["clothing.gloves_deadly"] = new[] { WearSlot.ForearmL, WearSlot.ForearmR, WearSlot.HandL, WearSlot.HandR, WearSlot.ShoulderL, WearSlot.ShoulderR, WearSlot.WristL, WearSlot.WristR },
            ["clothing.gloves_fit"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.gloves_fit_blue"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.gloves_fit_blue2"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.gloves_lace_tod"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.gloves_long_anarchy"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL, WearSlot.HandR, WearSlot.HandL },
            ["clothing.gloves_osiris"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.gloves_stars"] = new[] { WearSlot.ForearmR, WearSlot.ForearmL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.gloves_strap_anarchy"] = new[] { WearSlot.WristR, WearSlot.WristL, WearSlot.HandR, WearSlot.HandL },
            ["clothing.gloves_strap_anarchy_brn"] = new[] { WearSlot.WristR, WearSlot.WristL, WearSlot.HandR, WearSlot.HandL },
            ["clothing.greaves_tod"] = new[] { WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.halter_vamp"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.halter_vamp_blk_lea"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.halter_vamp_burgundy"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.halter_vamp_purple_lace"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.headband_primal"] = new[] { WearSlot.Head },
            ["clothing.headband_primal_2"] = new[] { WearSlot.Head },
            ["clothing.headband_primal_3"] = new[] { WearSlot.Head },
            ["clothing.headband_primal_4"] = new[] { WearSlot.Head },
            ["clothing.heels_luxury"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.heels_luxury_golden_color"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.heels_luxury_light_pink_color"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.heels_luxury_silver_color"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.heels_luxury_white_color"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.hipbelt_anarchy"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.jacket_autumn"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material01"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material02"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material03"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material04"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material05"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material06"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material07"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material08"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material09"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material10"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material11"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material12"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material13"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material14"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material15"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material16"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material17"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_autumn_jacket_material18"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_biker"] = new[] { WearSlot.Neck, WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jacket_cindy"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.jacket_ranger"] = new[] { WearSlot.Neck, WearSlot.Chest, WearSlot.Belly },
            ["clothing.jacket_tek"] = new[] { WearSlot.Neck, WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.jackettied_tek"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.jeans_skinny"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.keikogi_fighter"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.leggings_idol"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_idol_blue"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_01_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_02_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_03_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_04_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_05_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_06_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_07_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_08_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_09_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.leggings_yoga_10_pants"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.necklace_beads"] = new[] { WearSlot.Neck },
            ["clothing.necklace_osiris"] = new[] { WearSlot.Neck },
            ["clothing.outfit_reiko"] = new[] { WearSlot.Pelvis, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.outfit_reiko_default"] = new[] { WearSlot.Pelvis, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL, WearSlot.WristR, WearSlot.WristL },
            ["clothing.pants_anarchy"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.pants_anarchy_black"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.pants_biker"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.pants_fighter"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.pants_ranger"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.pants_stars"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.pendant_amy"] = new[] { WearSlot.Neck },
            ["clothing.pumps_flair"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_black"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_cherry"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_red"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_salmon"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_silver"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_sky"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_tan"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_white"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer1_style_01_yellow"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_black"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_cherry"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_red"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_salmon"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_silver"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_sky"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_tan"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_white"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer2_style_02_yellow"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_black"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_cherry"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_red"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_salmon"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_silver"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_sky"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_tan"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_white"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer3_style_03_yellow"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_black"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_cherry"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_red"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_salmon"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_silver"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_sky"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_tan"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_white"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sandals_summer4_style_04_yellow"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.scarf_classic"] = new[] { WearSlot.Neck, WearSlot.Chest },
            ["clothing.shirt_amy"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.shirt_amy_07"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.shirt_amy_08"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.shirt_riot"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.shirt_riot_greydark"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.shirt_riot_pink"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.shirt_riot_wine"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.shoes_tod"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.shorts_cindy"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_classic"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_deadly"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.shorts_fit"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_1_blackblue"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_1_blacklime"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_1_blackpink"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_1_blackwhite"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_2_black"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_3_black"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_3_blackgreen"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_3_blackmagenta"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_3_blackorange"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_3_magenta"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_3_orange"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_3_turquoise"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_3_white"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_4_batik1"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_4_batik2"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_4_batik3"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_4_batik4"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_4_batik5"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_fit_4_camouflage"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_osiris"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_riot"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.shorts_riot_brown"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.shorts_riot_denimgrey"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.shorts_riot_green"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.shorts_summer"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_vamp"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_vamp_blk_lea"] = new[] { WearSlot.Pelvis },
            ["clothing.shorts_vamp_blk_lea_lace"] = new[] { WearSlot.Pelvis },
            ["clothing.skirt_alloy"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_amy"] = new[] { WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_amy_04"] = new[] { WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_amy_05"] = new[] { WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_anarchy"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_anarchy_red"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_flair"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_flair_skirt_02"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_flair_skirt_03"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.skirt_jane"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_jane_blacks"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_jane_blues"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_jane_bluest"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_jane_lavendar"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_jane_reds"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_jane_redst"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_jane_rosey"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_jane_roseyt"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.skirt_naughty"] = new[] { WearSlot.Pelvis },
            ["clothing.skirt_naughty_skirt_2"] = new[] { WearSlot.Pelvis },
            ["clothing.skirt_naughty_skirt_3"] = new[] { WearSlot.Pelvis },
            ["clothing.skirt_naughty_skirt_4"] = new[] { WearSlot.Pelvis },
            ["clothing.skirt_naughty_skirt_5"] = new[] { WearSlot.Pelvis },
            ["clothing.skirt_naughty_skirt_6"] = new[] { WearSlot.Pelvis },
            ["clothing.skirt_primal"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.skirt_primal_1"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.skirt_primal_2"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.skirt_primal_3"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.skirt_wild"] = new[] { WearSlot.Pelvis },
            ["clothing.sleeves_idol"] = new[] { WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.slipons_fads"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_checks"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_graffiti"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_ladybugs"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_navy"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_pink"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_plaid"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_planets"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_red"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_skulls"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.slipons_fads_white"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_canvas"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_canvas_rs5_mat02"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_canvas_rs5_mat03"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_nerd"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_nerd_nc_sneakers_pink"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_nerd_nc_sneakers_purple"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_sport"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_sport_cream_white"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.sneakers_sport_lilac_purple"] = new[] { WearSlot.FootR, WearSlot.FootL },
            ["clothing.suit_bandaid"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.suit_bandaid_bs_bluemesh"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.suit_bandaid_bs_blueshine"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.suit_bandaid_bs_pinkmesh"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.suit_bandaid_bs_pinkshine"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.suit_bandaid_bs_purplemesh"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.suit_bandaid_bs_purpleshine"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis },
            ["clothing.sunglasses_luxury"] = new[] { WearSlot.Head },
            ["clothing.sunglasses_luxury_animal_print_color"] = new[] { WearSlot.Head },
            ["clothing.sunglasses_luxury_burgundy_color"] = new[] { WearSlot.Head },
            ["clothing.sunglasses_luxury_light_peach_color"] = new[] { WearSlot.Head },
            ["clothing.sunglasses_luxury_rainbow_color"] = new[] { WearSlot.Head },
            ["clothing.sunglasses_luxury_sunset_color"] = new[] { WearSlot.Head },
            ["clothing.sunglasses_luxury_with_color"] = new[] { WearSlot.Head },
            ["clothing.sweater_flair"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.sweater_flair_sweater_02"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.sweater_flair_sweater_03"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.sweater_naughty"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.sweater_naughty_sweater_2"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.sweater_naughty_sweater_3"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.sweater_naughty_sweater_4"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.sweater_naughty_sweater_5"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.sweater_naughty_sweater_6"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.tank_jane"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tank_jane_black"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tank_jane_blues"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tank_jane_lavendar"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tank_jane_reds"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tank_jane_rosey"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tanktop_summer"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tanktop_summer_i13sw_tank_02"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tanktop_summer_i13sw_tank_03"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tanktop_summer_i13sw_tank_04"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.tanktop_summer_i13sw_tank_05"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.thighboots_amy"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.top_alloy"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.top_anarchy"] = new[] { WearSlot.Chest },
            ["clothing.top_anarchy_bra_purple"] = new[] { WearSlot.Chest },
            ["clothing.top_anarchy_bra_red"] = new[] { WearSlot.Chest },
            ["clothing.top_anarchy_red"] = new[] { WearSlot.Chest },
            ["clothing.top_classic"] = new[] { WearSlot.Chest },
            ["clothing.top_deadly"] = new[] { WearSlot.Chest },
            ["clothing.top_fighter"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.top_folk"] = new[] { WearSlot.Neck, WearSlot.Chest, WearSlot.Belly },
            ["clothing.top_osiris"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.top_primal"] = new[] { WearSlot.Chest },
            ["clothing.top_primal_1"] = new[] { WearSlot.Chest },
            ["clothing.top_primal_2"] = new[] { WearSlot.Chest },
            ["clothing.top_primal_3"] = new[] { WearSlot.Chest },
            ["clothing.top_stars"] = new[] { WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.top_tod"] = new[] { WearSlot.Neck, WearSlot.Chest, WearSlot.ShoulderR, WearSlot.ShoulderL, WearSlot.ForearmR, WearSlot.ForearmL },
            ["clothing.top_yoga"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_01_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_02_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_03_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_04_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_05_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_06_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_07_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_08_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_09_top"] = new[] { WearSlot.Chest },
            ["clothing.top_yoga_10_top"] = new[] { WearSlot.Chest },
            ["clothing.tshirt_big"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_bt_charcoal"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_bt_dusty_blue"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_bt_dusty_pink"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_bt_dusty_purple"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_bt_grey"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_bt_red"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_bt_sky_blue"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_bt_white"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_american"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_born_to_ride"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_california"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_denim"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_eagles"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_heartbreaker"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_lost_angels"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_queen"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_racing"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_big_tshirt_saints"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.Pelvis, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_summer"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_summer_i13sw_tshirt_02"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_summer_i13sw_tshirt_03"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_summer_i13sw_tshirt_04"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tshirt_summer_i13sw_tshirt_05"] = new[] { WearSlot.Chest, WearSlot.Belly, WearSlot.ShoulderR, WearSlot.ShoulderL },
            ["clothing.tutu_nerd"] = new[] { WearSlot.Belly, WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL },
            ["clothing.vest_ranger"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.vest_ranger_green"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.vest_ranger_packs"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["clothing.vest_stars"] = new[] { WearSlot.Neck, WearSlot.Chest },
            ["clothing.wrapboots_primal"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.wrapboots_primal_1"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.wrapboots_primal_2"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.wrapboots_primal_3"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["clothing.yogapants_tek"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.yogapants_tek_yoga_01_black_mesh"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.yogapants_tek_yoga_02_black"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.yogapants_tek_yoga_03_black_red"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.yogapants_tek_yoga_04_black_orange"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.yogapants_tek_yoga_05_black_pink"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.yogapants_tek_yoga_06_black_blue"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.yogapants_tek_yoga_07_black_plain"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["clothing.yogapants_tek_yoga_08_white_plain"] = new[] { WearSlot.Pelvis, WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["gear.backpack_osiris"] = new[] { WearSlot.Chest },
            ["gear.backpack_riot"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["gear.backpack_riot_denim"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["gear.backpack_riot_grey"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["gear.backpack_riot_leather"] = new[] { WearSlot.Chest, WearSlot.Belly },
            ["gear.beltpouch_ranger"] = new[] { WearSlot.Pelvis },
            ["underwear.bikini_briefs"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.bikini_briefs_mat01"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.bikini_briefs_mat02"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.bikini_briefs_mat03"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.bikini_briefs_mat04"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.bikini_briefs_mat05"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.bikini_top"] = new[] { WearSlot.Chest },
            ["underwear.bikini_top_mat01"] = new[] { WearSlot.Chest },
            ["underwear.bikini_top_mat02"] = new[] { WearSlot.Chest },
            ["underwear.bikini_top_mat03"] = new[] { WearSlot.Chest },
            ["underwear.bikini_top_mat04"] = new[] { WearSlot.Chest },
            ["underwear.bikini_top_mat05"] = new[] { WearSlot.Chest },
            ["underwear.bra_lace"] = new[] { WearSlot.Chest },
            ["underwear.bra_lace_dream_lace_3_bra_black"] = new[] { WearSlot.Chest },
            ["underwear.bra_openback"] = new[] { WearSlot.Neck, WearSlot.Chest },
            ["underwear.bra_openback_bra_2"] = new[] { WearSlot.Neck, WearSlot.Chest },
            ["underwear.bra_openback_bra_3"] = new[] { WearSlot.Neck, WearSlot.Chest },
            ["underwear.bra_openback_bra_4"] = new[] { WearSlot.Neck, WearSlot.Chest },
            ["underwear.bra_openback_bra_5"] = new[] { WearSlot.Neck, WearSlot.Chest },
            ["underwear.bra_openback_bra_6"] = new[] { WearSlot.Neck, WearSlot.Chest },
            ["underwear.bra_riot"] = new[] { WearSlot.Chest },
            ["underwear.bra_riot_blue"] = new[] { WearSlot.Chest },
            ["underwear.bra_riot_pink"] = new[] { WearSlot.Chest },
            ["underwear.bra_riot_red"] = new[] { WearSlot.Chest },
            ["underwear.bra_strappy"] = new[] { WearSlot.Chest },
            ["underwear.bra_strappy_mat01"] = new[] { WearSlot.Chest },
            ["underwear.bra_strappy_mat02"] = new[] { WearSlot.Chest },
            ["underwear.bra_strappy_mat03"] = new[] { WearSlot.Chest },
            ["underwear.bra_strappy_mat04"] = new[] { WearSlot.Chest },
            ["underwear.bra_wild"] = new[] { WearSlot.Chest },
            ["underwear.briefs_cindy"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_flair"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_flair_panty_02"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_flair_panty_03"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_lace"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_lace_dream_lace_3_panty_black"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_lace_dream_lace_3_panty_blue1"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_lace_dream_lace_3_panty_blue2"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_luxury"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_luxury_02_cherry_panties"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_luxury_03_white_panties"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_luxury_04_black_panties"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_luxury_05_golden_panties"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_openback"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_openback_panties_2"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_openback_panties_3"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_openback_panties_4"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_openback_panties_5"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_openback_panties_6"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain_mat01"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain_mat02"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain_mat03"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain_mat04"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain_shima01"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain_shima02"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain_shima03"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_plain_shima04"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_primal"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_primal_panty1"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_primal_panty2"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_primal_panty3"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sport"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sport_panties_2"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sport_panties_3"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sport_panties_4"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sport_panties_5"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sport_panties_6"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_strappy"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_strappy_mat01"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_strappy_mat02"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_strappy_mat03"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_strappy_mat04"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety_01panty"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety_02_panty"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety_03_panty"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety_04panty"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety_05panty"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety_06panty"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety_07panty"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_sweety_08panty"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.briefs_teez"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_charcoal"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_dark_grey"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_dusty_blue"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_dusty_pink"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_dusty_purple"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_grey"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_red"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_sky_blue"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_teez_bt_panty_white"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot01"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot02"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot03"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot04"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot05"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot06"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot07"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot08"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot09"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot10"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot11"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_vapor_bot12"] = new[] { WearSlot.Pelvis },
            ["underwear.briefs_wild"] = new[] { WearSlot.Pelvis },
            ["underwear.kneesocks_nerd"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.kneesocks_nerd_nc_sock_left_argyle"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.kneesocks_nerd_nc_sock_left_polka_dots"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.kneesocks_nerd_nc_sock_right_hearts"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.kneesocks_nerd_nc_sock_right_polka_dots"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.panty_tod"] = new[] { WearSlot.Belly, WearSlot.Pelvis },
            ["underwear.socks_fit"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.socks_fit_blue"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.socks_fit_blue2"] = new[] { WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.sportsbra_jmr"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_jmr_bra_2"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_jmr_bra_3"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_jmr_bra_4"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_jmr_bra_5"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_jmr_bra_6"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_01_apply_black_bottom_trim"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_01_apply_black_trim"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_01_apply_white_bottom_trim"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_01_apply_white_trim"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_02_black"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_03_orange_black"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_04_red_black"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_05_black_pink"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_06_blue_black"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_07_blue_black_orange"] = new[] { WearSlot.Chest },
            ["underwear.sportsbra_tek_bra_08_white"] = new[] { WearSlot.Chest },
            ["underwear.stockings_overknee"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["underwear.stockings_overknee_over_knee_2"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["underwear.stockings_overknee_over_knee_3"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["underwear.stockings_overknee_over_knee_4"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["underwear.stockings_overknee_over_knee_5"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["underwear.stockings_overknee_over_knee_6"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["underwear.stockings_riot"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_riot_clear"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_01"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_02"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_03"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_04"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_05"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_06"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_07"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_08"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_09"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_10"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_11"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_13"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_14"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_15"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_16"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_17"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_spooky_18"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL, WearSlot.FootR, WearSlot.FootL },
            ["underwear.stockings_tod"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["underwear.swimsuit_briefs"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_2"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_3"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_4"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_5"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_6"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_black"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_blue"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_green"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_pink"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_red"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_briefs_bottom_white"] = new[] { WearSlot.Pelvis },
            ["underwear.swimsuit_top"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_blue"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_green"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_pink"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_red"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_1"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_2"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_3"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_4"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_5"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_6"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_black"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_blue"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_green"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_pink"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_red"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_top_white"] = new[] { WearSlot.Chest },
            ["underwear.swimsuit_top_white"] = new[] { WearSlot.Chest },
            ["underwear.thong_anarchy"] = new[] { WearSlot.Pelvis },
            ["underwear.thong_anarchy_purple"] = new[] { WearSlot.Pelvis },
            ["underwear.tights_deadly"] = new[] { WearSlot.ThighR, WearSlot.ThighL, WearSlot.ShinR, WearSlot.ShinL },
            ["underwear.top_cindy"] = new[] { WearSlot.Chest },
            ["underwear.top_luxury"] = new[] { WearSlot.Chest },
            ["underwear.top_luxury_02_cherry_bra"] = new[] { WearSlot.Chest },
            ["underwear.top_luxury_03_white_bra"] = new[] { WearSlot.Chest },
            ["underwear.top_luxury_04_black_bra"] = new[] { WearSlot.Chest },
            ["underwear.top_luxury_05_golden_bra"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_01"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_02"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_03"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_04"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_05"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_06"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_07"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_08"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_09"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_10"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_11"] = new[] { WearSlot.Chest },
            ["underwear.top_vapor_12"] = new[] { WearSlot.Chest },
        };

        /// <summary>
        /// Kill-switch (§52.9). False reverts every displacement site to the old
        /// coarse `Covers` test — the pre-slot behaviour — without touching the
        /// call sites. Kept for A/B soaks and as a one-flip escape hatch if the
        /// finer model ever misbehaves in play.
        /// </summary>
        public static bool Enabled = true;

        public static bool Has(string definitionId) =>
            Enabled && definitionId != null && Slots.ContainsKey(definitionId);

        public static IReadOnlyList<WearSlot> For(string definitionId) =>
            definitionId != null && Slots.TryGetValue(definitionId, out var s)
                ? s
                : System.Array.Empty<WearSlot>();

        /// <summary>
        /// Do these two garments occupy an overlapping spot on the body? This is
        /// the ONE occupancy predicate every displacement site must use (it does
        /// NOT test the wear layer — callers own that). Prefers the fine slot
        /// data; falls back to the coarse protection zones only when either side
        /// has no authored slots.
        /// </summary>
        public static bool SameSpot(ObjectDefinition a, ObjectDefinition b)
        {
            if (a is null || b is null)
            {
                return false;
            }

            if (Has(a.Id) && Has(b.Id))
            {
                foreach (var slot in Slots[a.Id])
                {
                    foreach (var other in Slots[b.Id])
                    {
                        if (slot == other)
                        {
                            return true;
                        }
                    }
                }

                return false;
            }

            foreach (var part in a.Covers)
            {
                if (b.Covers.Contains(part))
                {
                    return true;
                }
            }

            return false;
        }
    }

    // The body spots a garment can occupy — mirrors the prefab-side
    // VisualWearSlot enum name-for-name (spec §52.9).
    public enum WearSlot
    {
        Head,
        EarR,
        EarL,
        Neck,
        Chest,
        ShoulderR,
        ShoulderL,
        ForearmR,
        ForearmL,
        Belly,
        WristR,
        WristL,
        Pelvis,
        HandR,
        HandL,
        ThighR,
        ThighL,
        ShinR,
        ShinL,
        FootR,
        FootL
    }
}
