#!/usr/bin/env python3
"""Mechanically export the canonical §67.7 calibration for runtime agent speech."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
profile = json.loads((root / '_ArtSource/Voice/lipsync_profile.json').read_text())
mapping = json.loads((root / '_ArtSource/Voice/letter_visemes.json').read_text())
names = [p['name'] for p in profile['phonemes']]
lines = ['// GENERATED by Tools/export_runtime_lipsync.py; calibration lives in _ArtSource/Voice.',
         'using System.Collections.Generic;',
         'namespace HexLive.UnityPresentation.Audio', '{',
         'internal static class RuntimeVoiceCalibration', '{']
for key in ['sourceSampleRate', 'targetSampleRate', 'sampleCount', 'melFilterBankChannels', 'mfccNum', 'fps']:
    lines.append(f'    internal const int {key[0].upper() + key[1:]} = {profile[key]};')
for key in ['minVolume', 'maxVolume']:
    lines.append(f'    internal const double {key[0].upper() + key[1:]} = {profile[key]};')
lines += ['    internal static readonly double[][] Templates = {']
for phone in profile['phonemes']:
    lines.append('        new double[] { ' + ', '.join(str(x) for x in phone['mfcc']) + ' },')
lines += ['    };']
for field, keytype in [('letters', 'char'), ('digraphs', 'string')]:
    lines += [f'    internal static readonly Dictionary<{keytype}, int> {field.title()} = new()', '    {']
    for key, value in mapping[field].items():
        literal = repr(key) if keytype == 'char' else json.dumps(key)
        index = -2 if value == 'skip' else names.index(value)
        lines.append(f'        [{literal}] = {index},')
    lines += ['    };']
lines += ['}', '}']
target = root / 'Assets/HexLive/UnityPresentation/Audio/RuntimeVoiceCalibration.cs'
target.write_text('\n'.join(lines) + '\n')
print('Exported runtime voice calibration from canonical profile and letter map.')
