// GENERATED by Tools/export_runtime_lipsync.py; calibration lives in _ArtSource/Voice.
using System.Collections.Generic;
namespace HexLive.UnityPresentation.Audio
{
internal static class RuntimeVoiceCalibration
{
    internal const int SourceSampleRate = 44100;
    internal const int TargetSampleRate = 16000;
    internal const int SampleCount = 1024;
    internal const int MelFilterBankChannels = 26;
    internal const int MfccNum = 12;
    internal const int Fps = 60;
    internal const double MinVolume = -3.0;
    internal const double MaxVolume = -1.0;
    internal static readonly double[][] Templates = {
        new double[] { 14.0, -3.9499999999999997, -1.35, -0.9500000000000001, 0.8, -0.6, 0.45, -0.35, 0.15, -0.55, 0.25, -0.15 },
        new double[] { 11.625, -1.325, 3.65, -2.375, -1.9000000000000001, 1.65, -1.1, 0.725, -0.425, 0.45, -0.65, 0.45 },
        new double[] { 12.65, -5.05, -2.65, 2.075, -0.2, -1.4, 0.675, 0.9, -0.725, 0.35, -0.35, 0.25 },
        new double[] { 12.625, -2.625, 2.075, -0.925, -1.2, 1.1, -0.425, 0.45, 0.65, -0.35, 0.25, -0.55 },
        new double[] { 13.85, -5.65, -1.35, 1.075, 1.4, -1.9000000000000001, 0.9, -0.9, 0.45, -0.35, 0.45, -0.25 },
        new double[] { 5.375, -0.9, -0.425, 0.275, 0.25, -0.15, 0.05, 0.05, -0.15, 0.05, -0.1, 0.05 },
        new double[] { 5.9, 0.39999999999999997, 1.4, -0.9, 0.7, 1.1, -0.425, 0.35, 0.725, -0.25, 0.45, -0.25 },
        new double[] { 4.375, 1.4, 1.9000000000000001, -0.425, 1.4, 1.9000000000000001, -0.9, 0.725, 1.4, 0.425, 0.9, -0.425 },
        new double[] { 4.9, 0.7, 0.9, 0.39999999999999997, 0.9, 1.4, -0.2, 1.1, 0.7, 0.25, 0.45, -0.15 },
        new double[] { 6.35, 0.1, 0.7, -0.2, 0.39999999999999997, 0.2, 0.7, -0.25, 0.425, 0.25, 0.15, -0.15 },
        new double[] { 9.9, -2.875, 0.39999999999999997, 0.9, -0.39999999999999997, -0.7, 0.375, 0.425, -0.15, 0.35, -0.25, 0.15 },
        new double[] { 10.35, -1.9000000000000001, 0.9, -0.2, -0.7, 0.39999999999999997, 0.275, 0.225, 0.35, -0.05, 0.15, -0.25 },
        new double[] { 6.9, -1.4, -0.39999999999999997, 1.4, 0.7, -0.39999999999999997, 0.9, -0.7, 0.25, 0.45, -0.15, 0.25 },
        new double[] { 5.4, 0.7, 1.1, -0.2, 0.2, 0.7, 0.39999999999999997, 0.25, 0.45, 0.05, 0.25, -0.05 },
    };
    internal static readonly Dictionary<char, int> Letters = new()
    {
        ['a'] = 0,
        ['e'] = 3,
        ['i'] = 1,
        ['o'] = 4,
        ['u'] = 2,
        ['y'] = 1,
        ['j'] = 1,
        ['p'] = 5,
        ['b'] = 5,
        ['m'] = 5,
        ['f'] = 6,
        ['v'] = 6,
        ['s'] = 7,
        ['z'] = 7,
        ['c'] = 7,
        ['t'] = 9,
        ['d'] = 9,
        ['n'] = 9,
        ['r'] = 10,
        ['l'] = 11,
        ['k'] = 12,
        ['g'] = 12,
        ['h'] = -2,
    };
    internal static readonly Dictionary<string, int> Digraphs = new()
    {
        ["sh"] = 8,
        ["ch"] = 8,
        ["zh"] = 8,
        ["th"] = 13,
        ["nh"] = 5,
    };
}
}
